theme: jekyll-theme-cayman
title: Github Pages Test Site 2017
description: Using GitHub Pages the new way

gems:
   - jekyll-mentions
   - jemoji
   - jekyll-redirect-from
   - jekyll-sitemap
   - jekyll-feed
